apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  nodeSelector:
    cpucounts: 4
  containers:
  - name: nginx
    image: docker.io/library/nginx     
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
