apiVersion: v1
kind: Pod
metadata:
  name: testschduler
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchWxpressions:
          - key: area
            operator: In
            values:
            - test1
            - test2
  containers:
  - name: myapp
    image: nginx
