apiVersion: v1
kind: Pod
metadata:
  name: testschduler
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
        matchExpressions:
          - key: area
            operator: In
            values:
            - test1
            - test2
        topologyKey: kubernetes.io/hostname
